#! /bin/bash

# Set the hostname
echo "new-test-machine-`cat /proc/sys/kernel/random/uuid`" > $target/etc/hostname

# Create a local admin user
$ROOTCMD useradd --password $ROOTPW --groups adm,dialout,cdrom,plugdev,sudo -c "Local Admin,,," --shell /bin/bash deploy
$ROOTCMD mkdir /home/deploy
$ROOTCMD chmod 0700 /home/deploy
$ROOTCMD chown deploy:deploy /home/deploy
fcopy -ir /home/deploy

$ROOTCMD locale-gen en_US.UTF-8
$ROOTCMD update-locale LANG=en_US.UTF-8

# Basic network configuration
fcopy -v /etc/network/interfaces

# create userscript for installing rvm and ruby

cat >> $target/home/deploy/run_once.sh << EOF
  cd ~
  cat /dev/zero | ssh-keygen -q -N ""
  echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCwbH/kgQTFMXNWsevWZx6/XAjc4xmfmmatZWDdikRaqTnXYdxNbxz0gKgNGaMRgeZGLI7XtRB1n9FtlLmr7hcm0dtHwWgRiWe4fZ0V9NDivIADbzKSmkajcnJUQxuxQydOqruZrG1spqQ4ZqjIAHRj0uef56GygZFegSabYUvwP0KZbFgbPHsLnPcs1xowdsRywsZuy/dPL3lMQ56x6LW8Sy10wD3HCfZiUlp38IAzG/qOu+WQfolxgMHyfhAHA+Sf8CysujRUJdbJ2nTF1VBgFAw4VmwYMWtF+osR4LnTTGZFPQzzs3x6ZNwZP+TbP1EXfncAIP6bTHmpSkXkr6Tj andrew@Shenandoah.local" > ~/.ssh/authorized_keys
  echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsOJYmOukaWl8wAC2rgA4LsN/IU18inBoexym40/fPiQqH1/RUta+Vln/mN8VU5yrQZSVmtZ+iNPJDI+vdOuxkMMK1G9bp1A/vAJlWQTYKxaFOuGsZKwdhr04ldMdU8Os59NHjrGRdpRY2oiXy7HtwS/MwKyhAT/Aw8wy7XQ2wSZ1ahc2Y8w87fcRLJL/PoGzkuri2BwqpMKcH72fc2xRpJwHyQelEeCA6dx5ye5B6iUOMuelcSodY+JYFZj7cxEi1kr0f9OBZQPIA0Az63AjTK1OAXnZm9KOOxC6tuwQnybCqKfMhn5LysZO0PGDXiReZfR5N5FqkVzvuyMsZUIth chadb@revolutionintheair.local" >> ~/.ssh/authorized_keys
  echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3UhBDIyMg8NbOhf0HEN9rzrb03ANZrKAdOPTHFMQEBrrjMECMdQ0cAKazoIlLSue97QZ+6blZEGpjQ7DFDS+RPcgDdZg65TmqdBLM3qVqCTF96XpWFuMZWQrGX2jm/6EptaDsuIkQLcAcFK/1/ftpevOnx2I5yTz17qKDrhpiH72oW5aAmzz8HTkQzwWRjZFzQlNtPt736zzUcBP4obIuQhWtKPZXM4uqagyL+TjcfnRkn+vjElTZ+epfaL7ffaIS3TkSN/zRyN7/z80lYI80Q57nImHSsgUK+XD7sWwbmyOdmA9VDIfpkr4dp4Lcld50uB05AivAAO08FYiRE6xv chrisk@watchtower.beardendesigns.org" >> ~/.ssh/authorized_keys
  
  # Install RVM
  echo "Installing RVM with Ruby"

  gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
  \curl -sSL https://get.rvm.io | bash -s stable
  source /home/deploy/.rvm/scripts/rvm
  rvm install ruby-2.2.2
  rvm info

  echo "Ruby installed! (unless there were errors)"
  
  gem install bundler
  echo "Bundler installed too!"
  
  mkdir ~/Sites
  cd ~/Sites
  git clone https://github.com/beardendesigns/rollcall
  cd rollcall
  bundle
  
  # write out current crontab
  crontab -l > tmp_crontab
  # echo new cron into cron file
  echo "@reboot /bin/bash -lc \"cd \$HOME/Sites/rollcall; ruby server_info_control.rb start\"" >> tmp_crontab
  # install new cron file
  crontab tmp_crontab
  rm tmp_crontab
EOF

$ROOTCMD chmod 0755 /home/deploy/run_once.sh

$ROOTCMD su -c "cd /home/deploy && git clone https://github.com/chadb/.dotfiles.git && cd .dotfiles && ./link.sh" deploy

$ROOTCMD su -c "/home/deploy/run_once.sh" deploy

$ROOTCMD rm "/home/deploy/run_once.sh"
